# Generated by Django 6.0.3 on 2026-03-25 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='ID of the user from Users Service')),
                ('video_id', models.UUIDField(help_text='UUID of the video from Video Service')),
                ('watch_duration_seconds', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id'], name='analytics_w_user_id_e31c06_idx'), models.Index(fields=['video_id'], name='analytics_w_video_i_72c6bc_idx')],
            },
        ),
    ]
